server:
  port: 8084

spring:
  profiles:
    active: dev

  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    url: jdbc:postgresql://localhost:5432/bdeckdb
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

#logging:
#  level:
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG
